Repository puppetlabs/support-tasks, pull requests merged in 2021-07, with the labels that each got.

#101 Remove Tasks that are for EOL PE (SUP-2431)
  .github/workflows/nightly.yml
  README.md
  metadata.json
  spec/acceptance/st0244_disable_mco_logrotate_spec.rb
  tasks/st0244_disable_mco_logrotate.json
  tasks/st0244_disable_mco_logrotate.sh
  tasks/st0299_regen_master_cert.json
  tasks/st0299_regen_master_cert.sh
Labels: backwards-incompatible

#114 (SUP-2568) Only auto release if the changelog is updated
  .github/workflows/auto_release.yml
Labels: maintenance

#116 (SUP-1601) Add common postgres commands as tasks
  files/common.sh
  files/db_sizes.sql
  tasks/st1096_db_commands.json
  tasks/st1096_db_commands.sh
Labels: enhancement
