Repository puppetlabs/support-tasks, pull requests merged in 2022-05, with the labels that each got.

#140 (SUP-2836) Remove st0149_resolve_stack_level_too_deep
  .github/workflows/nightly.yml
  metadata.json
  tasks/st0149_resolve_stack_level_too_deep.json
  tasks/st0149_resolve_stack_level_too_deep.sh
Labels: backwards-incompatible

#138 Update spec helps to newer version
  spec/spec_helper_acceptance.rb
  spec/spec_helper_acceptance_local.rb
Labels: maintenance

#142 (SUP-2844) Update upload support script task
  tasks/st0305_support_script_and_upload.json
  tasks/st0305_support_script_and_upload.rb
Labels: enhancement

#143 (SUP-3284) Update Supported OS's
  metadata.json
Labels: maintenance
